apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: mi-api
  ports:
    - protocol: TCP
      port: 80  # Puerto expuesto
  type: LoadBalancer  # Expone el servicio externamente con balanceo de carga

